spring:
  application:
    name: "shopping"

discount:
  quantity:
    thresholds:
      - min: 1
        max: 9
        rate: 0.00
      - min: 10
        max: 19
        rate: 0.05
      - min: 20
        max: 49
        rate: 0.10
      - min: 50
        max: -1  # -1 to represent no upper limit
        rate: 0.15
  percentage:
    discountRate: 0.10